name: Build & Test Mesh

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install system dependencies
        run: sudo apt-get install libzmq5
      - name: Install esy
        run: npm install -g esy && ls
      - uses: esy/github-action@v1
        with:
          cache-key: mesh-build-${{ hashFiles('esy.lock/index.json') }}

  Esy-tests:
    needs: Build
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: 16
    
    - name: Install system dependencies
      run: sudo apt-get install libzmq5
    - name: Install esy
      run: npm install -g esy && ls

    - uses: esy/github-action@v1
      with:
        cache-key: mesh-build-${{ hashFiles('esy.lock/index.json') }}    
        
    - name: Run Mesh test suite
      run:
          esy test

  Draft-Release:
    needs: 
      - Build 
      - Esy-tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: release-drafter/release-drafter@v5
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
